In [1]:
import torch 

In [4]:
x = torch.tensor([[12.9382, 11.2081, 11.0942],
        [12.9211, 11.1199, 11.0261],
        [14.3441, 13.3287, 12.6234],
        [13.7739, 13.2769, 12.5926]], device='cuda:0')

In [20]:
p = torch.cumsum(x / x.sum(dim=-1, keepdim=True), dim=-1)

In [51]:
idx = torch.searchsorted(p, torch.rand([p.shape[0], 1]).to("cuda:0"))

In [52]:
idx

tensor([[2],
        [0],
        [1],
        [1]], device='cuda:0')

In [53]:
idx.shape

torch.Size([4, 1])

In [54]:
x.shape

torch.Size([4, 3])

In [56]:
x.gather(dim=1, index=idx)

tensor([[11.0942],
        [12.9211],
        [13.3287],
        [13.2769]], device='cuda:0')

In [ ]:
torch.stack([torch.cat([xi[:bpi], e, xi[bpi:]]) for xi, bpi in zip(x, bp)])

In [65]:
x= torch.tensor([[6031, 6031, 6031, 6047],
        [6031, 6031, 6031, 6046],
        [6047, 6047, 6047, 6046],
        [6046, 6046, 6046, 6012],
        [6046, 6046, 6046, 6013],
        [6012, 6012, 6012, 6008],
        [6013, 6013, 6013, 6031],
        [6008, 6008, 6008, 6031],
        [6031, 6031, 6031, 6031],
        [6031, 6031, 6031, 6046],
        [   0, 6031, 6031, 6046],
        [   0,    0, 6046,    0]], device='cuda:0')

pred_loc= torch.tensor([[6031],
        [6033],
        [6031],
        [6031]], device='cuda:0')

In [63]:
x.shape

torch.Size([12, 4])

In [80]:
x_after = torch.tensor([[6031, 6031, 6031, 6047],
        [6031, 6031, 6031, 6046],
        [6047, 6047, 6047, 6046],
        [6046, 6046, 6046, 6012],
        [6046, 6046, 6046, 6013],
        [6012, 6012, 6012, 6008],
        [6013, 6013, 6013, 6031],
        [6008, 6008, 6008, 6031],
        [6031, 6031, 6031, 6031],
        [6031, 6031, 6031, 6046],
        [6031, 6031, 6031, 6046],
        [   0, 6033, 6046, 6031],
        [   0,    0, 6031,    0]], device='cuda:0')
x_len_before = torch.tensor([9, 10, 11, 10], device='cuda:0')
x_len_after = torch.tensor([11, 12, 13, 12], device='cuda:0')

In [85]:
x_after

tensor([[6031, 6031, 6031, 6047],
        [6031, 6031, 6031, 6046],
        [6047, 6047, 6047, 6046],
        [6046, 6046, 6046, 6012],
        [6046, 6046, 6046, 6013],
        [6012, 6012, 6012, 6008],
        [6013, 6013, 6013, 6031],
        [6008, 6008, 6008, 6031],
        [6031, 6031, 6031, 6031],
        [6031, 6031, 6031, 6046],
        [6031, 6031, 6031, 6046],
        [   0, 6033, 6046, 6031],
        [   0,    0, 6031,    0]], device='cuda:0')

In [98]:
gen = torch.stack([xi[x_len_beforei:x_len_afteri] for xi, x_len_beforei, x_len_afteri in zip(x_after.transpose(1, 0), x_len_before, x_len_after)])

In [99]:
gen

tensor([[6031, 6031],
        [6031, 6033],
        [6046, 6031],
        [6046, 6031]], device='cuda:0')

In [101]:
torch.cat([gen, gen], dim=0)

tensor([[6031, 6031],
        [6031, 6033],
        [6046, 6031],
        [6046, 6031],
        [6031, 6031],
        [6031, 6033],
        [6046, 6031],
        [6046, 6031]], device='cuda:0')

In [86]:
for xi, x_len_beforei, x_len_afteri in zip(x_after.transpose(1, 0), x_len_before, x_len_after):
    print(xi, x_len_beforei, x_len_afteri)
    print(xi[x_len_beforei:x_len_afteri])
    break

tensor([6031, 6031, 6047, 6046, 6046, 6012, 6013, 6008, 6031, 6031, 6031,    0,
           0], device='cuda:0') tensor(9, device='cuda:0') tensor(11, device='cuda:0')
tensor([6031, 6031], device='cuda:0')
